defaults:
  - base
  - data: celeba
  - task: inpaint
  - model: flow_matching
  - model_type: generative
  - _self_

output:
  eval_freq: 20000

model:
  backbone:
    in_channels: 7 # noised RGB image + masked RGB input + mask
    out_channels: 3 # RGB image

optimizer:
  lr: 1e-4
  betas: [0.9, 0.95]

data:
  trainloader:
    # TODO: Need to adjust number of accumulate steps?
    batch_size: 32
  preprocess_fn:
    min_frac: 0.05
    max_frac: 0.05