# @package _global_

output:
  plotter:
    _target_: cdnp.plot.plotter.ColourisationPlotter
    _partial_: true
    device: ${runtime.device}
    num_samples: 16
    norm_means: ${data.dataset.norm_means}
    norm_stds: ${data.dataset.norm_stds}
    preprocess_fn: ${data.preprocess_fn}


data:
  preprocess_fn:
    _target_: cdnp.task.preprocess_colourisation
    _partial_: true